### ISSUE TITLE
之前可以用图标撤销隐私窗口关闭的标签的，最近突然不行了

### ISSUE THREAD

**Issue by aDon0000** [Sean-214/browser-extension-last-session#14]
我希望变回之前那样，毕竟浏览器自带的撤销不能撤回隐私窗口

**Comment by Sean-214** [comment]
撤销功能只是调用了 `chrome.sessions.getRecentlyClosed()` 和 `chrome.sessions.restore()` 这两个 API，可能是浏览器对 API 的功能做了调整吧，我也没办法的。我发现在隐私窗口中连自带的历史记录都没有的，并且我也觉得这样更隐私更安全。

**Comment by aDon0000** [comment]
https://chrome.google.com/webstore/detail/kmnmkpgmneeokldcmfcgjppgpcfecoed
这个还可以在隐私模式用，我现在暂时在用这个辅助
