### ISSUE TITLE
Thank you very much for making your extension for edge browser I have over 1200 tabs open what is the list of 25 represent is that sessions

### ISSUE THREAD

**Issue by dyingjedi** [Sean-214/browser-extension-last-session#3]
Thank you very much for making your extension for edge browser I have over 1200 tabs open what is the list of 25 represent is that sessions? What is it meaning the amount of times that are literally saved because this extension will not work for me if that is the case!

**Comment by Sean-214** [comment]
"Recently closed list size": This setting only sets  the size of "Recently Closed" Popup, not "Last Session" Page. But for "Last Session" I didn't try so many tabs, 30 tabs are OK. Storing too many tabs is not recommended. This function is similar to the Maxthon browser.
